version: "3.7"

services:

  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile.dev
    tty: true
    command: ["./wait-for-it.sh", "--timeout=0", "localhost:8000", "--", "nginx", "-g", "daemon off;"]
    depends_on:
      - app
    network_mode: host
    # To allow resolution of compose assigned app name on host - outside compose network.
    extra_hosts:
      mattermost-docker_app_1: 127.0.0.1
    # For reference only (as all open with network_mode host).
    ports:
      - 443:443
      - 80:80

  app:
    build:
      context: app
      args:
        - edition=team
    volumes:
      - mm-data:/mattermost/config:rw
      - mm-data:/mattermost/data:rw
      - mm-data:/mattermost/logs:rw
      - mm-data:/mattermost/plugins:rw
      - mm-data:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - DB_HOST=localhost
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json
    network_mode: host
    ports:
      - 8000:8000

  db:
    build: db
    read_only: true
    volumes:
      - mm-dbdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    network_mode: host
    ports:
      - 53:53

volumes:
  mm-dbdata:
  mm-data:
