version: "3.7"

services:

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.demo
    tty: true
    command: ["./wait-for-it.sh", "--timeout=0", "mattermost-docker_app_1:8000", "--", "nginx", "-g", "daemon off;"]
    depends_on:
      - app
    ports:
      - '8000:443'

  app:
    build:
      context: app
      args:
        - edition=team
    volumes:
      - mm-data:/mattermost/config:rw
      - mm-data:/mattermost/data:rw
      - mm-data:/mattermost/logs:rw
      - mm-data:/mattermost/plugins:rw
      - mm-data:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      MM_USERNAME: ${MM_USERNAME}
      MM_PASSWORD: ${MM_PASSWORD}
      MM_DBNAME: ${MM_DBNAME}
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json
    extra_hosts:
      danvers: 172.21.0.1

  db:
    build: db
    read_only: true
    volumes:
      - mm-dbdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  mm-dbdata:
  mm-data:

networks:
  default:
    external:
      name: ui_network
